apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubernetes-networks
  namespace: argo
spec:
  destination:
    namespace: homework
    server: https://kubernetes.default.svc
  project: otus-copy
  source:
    path: kubernetes-networks
    repoURL: https://github.com/slv-alt/otus-copy.git
    targetRevision: HEAD