apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: otus-copy
  namespace: argo
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - name: in-cluster
    namespace: '*'
    server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - https://github.com/slv-alt/otus-copy.git